const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),{pathToFileURL}=require('node:url');
require('../scripts/runtime.js');require('../scripts/codex-bridge.js');
const modulePath=path.resolve(__dirname,'../scripts/node-journal.mjs');
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'nu-journal-test-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const {createNodeJournal}=await import(pathToFileURL(modulePath));return {root,createNodeJournal,journal:createNodeJournal(root)};}
test('Node journal atomically elects one writer and survives a new instance',async t=>{const {journal,root,createNodeJournal}=await fixture(t);const claims=await Promise.all(Array.from({length:8},()=>journal.claim('same',{status:'pending'})));assert.equal(claims.filter(Boolean).length,1);await journal.put('same',{status:'verified',result:{id:'page'}});assert.equal((await createNodeJournal(root).get('same')).result.id,'page');});
test('uncertain Node journal is recoverable only with remote evidence',async t=>{const {journal}=await fixture(t);await journal.claim('x',{status:'uncertain'});await assert.rejects(journal.reset('x',''),/REMOTE_EVIDENCE/);assert.equal(await journal.claim('x',{}),false);await journal.reset('x','Remote page readback confirmed not applied');assert.equal(await journal.claim('x',{status:'pending'}),true);});
test('cloud Node bridge executes create and receipt replay without a shell tool',async t=>{
 const {root}=await fixture(t),AsyncFunction=Object.getPrototypeOf(async()=>{}).constructor;
 const runNode=async code=>{let output='';await new AsyncFunction('nodeRepl',code)({write:s=>output+=s});return {content:[{type:'text',text:output}]};};
 const journal=createNodeJournalBridge(runNode,modulePath,root);let writes=0;
 const content='这是一句总结。\n说明内容。';
 const tools={read:async a=>a.id.startsWith('notion:')?{text:'spec'}:{text:'<content>\n'+content+'\n</content>',url:'https://app.notion.com/p/'+'1'.repeat(32),icon:{type:'external'},cover:{type:'external'}},write:async()=>{writes++;return {pages:[{id:'1'.repeat(32)}]};}};
 const client=createNotionUse(tools,[{name:'read'},{name:'write'}],null,null,{journal,bindings:{fetch:'read',create_pages:'write'}});
 const plan={operationId:'cloud-create',privateRoot:true,visibility:'private',documentType:'summary',title:'Cloud note',content,icon:'https://example.test/i.png',cover:'https://example.test/c.png',visuals:{aiGenerated:true,inspected:true,prompt:'cards'}};
 assert.equal((await client.create(plan)).status,'verified');assert.equal((await client.create(plan)).reused,true);assert.equal(writes,1);
});
test('missing persistence stops before any Notion write',async()=>{let calls=0;const client=createNotionUse({write:async()=>calls++},[{name:'write'}],null,null,{bindings:{create_pages:'write'}});await assert.rejects(client.create({operationId:'no-store'}),/PERSISTENT_JOURNAL_UNAVAILABLE/);assert.equal(calls,0)});
test('bridge strips raw visual metadata before persistence',async()=>{let persisted;const fake={get:async()=>null,claim:async()=>true,put:async(k,v)=>{persisted=v}};const content='摘要。';const tools={read:async a=>a.id.startsWith('notion:')?{}:{text:'<content>'+content+'</content>',url:'https://app.notion.com/p/'+'1'.repeat(32),icon:{url:'do-not-save'},cover:{url:'do-not-save'}},write:async()=>({pages:[{id:'1'.repeat(32)}]})};const c=createNotionUse(tools,[{name:'read'},{name:'write'}],null,null,{journal:fake,bindings:{fetch:'read',create_pages:'write'}});await c.create({operationId:'safe',privateRoot:true,visibility:'private',documentType:'summary',title:'A',content,icon:'https://example.test/i.png',cover:'https://example.test/c.png',visuals:{aiGenerated:true,inspected:true,prompt:'a'}});assert.ok(!JSON.stringify(persisted).includes('do-not-save'));});
test('interrupted unpublished writes cannot block receipt reuse or the next claim',async t=>{const {journal,root,createNodeJournal}=await fixture(t),{createHash}=require('node:crypto');await journal.claim('done',{status:'pending'});await journal.put('done',{status:'verified',result:{id:'page'}});const dir=path.join(root,createHash('sha256').update('done').digest('hex'));await fs.writeFile(path.join(dir,'.pending-interrupted-process'),'{');const reopened=createNodeJournal(root);assert.equal((await reopened.get('done')).status,'verified');assert.equal(await reopened.claim('done',{status:'pending'}),false);const fresh=path.join(root,createHash('sha256').update('new').digest('hex'));await fs.mkdir(fresh);await fs.writeFile(path.join(fresh,'.pending-interrupted-process'),'{');assert.equal(await reopened.claim('new',{status:'pending'}),true);});
